org: metart43
app: bot4radiohead
service: radiohead-twitter-bot

provider:
  name: aws
  runtime: nodejs12.x

custom:
  env: ${file(./creds.yml)}

# package:
#   exclude:
#     - node_modules/chrome-aws-lambda/**

plugins:
  - serverless-offline

functions:
  bot:
    handler: handler.bot
    timeout: 30
    # layers:
    #   - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:19
    events:
      - schedule: cron(22 22 * * ? *)
    environment:
      TWITTER_API_KEY: ${self:custom.env.TWITTER_API_KEY}
      TWITTER_API_SECRET: ${self:custom.env.TWITTER_API_SECRET}
      ACCESS_TOKEN: ${self:custom.env.ACCESS_TOKEN}
      ACCESS_TOKEN_SECRET: ${self:custom.env.ACCESS_TOKEN_SECRET}
      SPOTIFY_CLIENT_SECRET: ${self:custom.env.SPOTIFY_CLIENT_SECRET}
      SPOTIFY_CLIENT_ID: ${self:custom.env.SPOTIFY_CLIENT_ID}
