org: metart43
app: bot4radiohead
service: radiohead-twitter-bot

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    TWITTER_API_KEY: ${param:TWITTER_API_KEY}
    TWITTER_API_SECRET: ${param:TWITTER_API_SECRET}
    ACCESS_TOKEN: ${param:ACCESS_TOKEN}
    ACCESS_TOKEN_SECRET: ${param:ACCESS_TOKEN_SECRET}
    SPOTIFY_CLIENT_SECRET: ${param:SPOTIFY_CLIENT_SECRET}
    SPOTIFY_CLIENT_ID: ${param:SPOTIFY_CLIENT_ID}

package:
  exclude:
    - node_modules/chrome-aws-lambda/**
    - node_modules/puppeteer/**
    - node_modules/puppeteer-core/**

functions:
  bot:
    handler: handler.bot
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:18
  listen:
    handler: listen.stream
    timeout: 30
